image: docker:latest
services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/ravepro/wsapi .
    - docker push registry.gitlab.com/ravepro/wsapi:latest
  only:
    - master
